pokemoncollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('pokemon/', views.pokemon_index, name='pokemon-index'),
    path('pokemon/<int:pokemon_id>', views.pokemon_detail, name='pokemon-detail'),
    path('pokemon/create/', views.PokemonCreate.as_view(), name='pokemon-create'),
    path('pokemon/<int:pk>/update/', views.PokemonUpdate.as_view(), name='pokemon-update'),
    path('pokemon/<int:pk>/delete/', views.PokemonDelete.as_view(), name='pokemon-delete'),
    path('pokemon/<int:pokemon_id>/add-feeding/', views.add_feeding, name='add-feeding'),
    path('items/create/', views.ItemCreate.as_view(), name='item-create'),
    path('items/<int:pk>/', views.ItemDetail.as_view(), name='item-detail'),
    path('items/', views.ItemList.as_view(), name='item-index'),
    path('items/<int:pk>/update/', views.ItemUpdate.as_view(), name='item-update'),
    path('items/<int:pk>/delete/', views.ItemDelete.as_view(), name='item-delete'),
    path('pokemon/<int:pokemon_id>/associate-item/<int:item_id>/', views.associate_item, name='associate-item'),
    path('pokemon/<int:pokemon_id>/remove-item/<int:item_id>/', views.remove_item, name='remove-item'),

]

pokemoncollector/pokemoncollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

pokemoncollector/main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Item(models.Model):
    name = models.CharField(max_length=50)
    effect = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("item-detail", kwargs={"pk": self.id})
    


class Pokemon(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    evolution = models.IntegerField()
    
    items = models.ManyToManyField(Item)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("pokemon-detail", kwargs={"pokemon_id": self.id})
    
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
    )
    
class Feeding(models.Model):
    date = models.DateField('Feeding Date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )
    
    pokemon = models.ForeignKey(Pokemon, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"

pokemoncollector/main_app/forms.py
from django import forms
from .models import Feeding

class FeedingForm(forms.ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

pokemoncollector/main_app/views.py
from django.shortcuts import render, redirect
from .models import Pokemon, Item
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from django.http import HttpResponse
# Create your views here.

from .forms import FeedingForm

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def pokemon_index(request):
    pokemon = Pokemon.objects.all()
    return render(request,'pokemon/index.html', {'pokemon': pokemon})

def add_feeding(request, pokemon_id):
    form = FeedingForm(request.POST)
    
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.pokemon_id = pokemon_id
        new_feeding.save()
    return redirect('pokemon-detail', pokemon_id=pokemon_id)

def pokemon_detail(request, pokemon_id):
    pokemon_from_db = Pokemon.objects.get(id=pokemon_id)
    items_pokemon_doesnt_have = Item.objects.exclude(id__in = pokemon_from_db.items.all().values_list('id'))
    feeding_form = FeedingForm()
    return render(request, 'pokemon/detail.html', {'pokemon': pokemon_from_db, 'feeding_form': feeding_form, 'items': items_pokemon_doesnt_have})

class PokemonCreate(CreateView):
    model = Pokemon
    fields = ['name','type', 'description', 'evolution']
    
class PokemonUpdate(UpdateView):
    model = Pokemon
    fields = ['name', 'description', 'evolution']
    
class PokemonDelete(DeleteView):
    model = Pokemon
    success_url = '/pokemon/'
    
class ItemCreate(CreateView):
    model = Item
    fields = '__all__'
    
class ItemList(ListView):
    model = Item
    
class ItemDetail(DetailView):
    model = Item
    
class ItemUpdate(UpdateView):
    model = Item
    fields = ['name', 'effect']
    
class ItemDelete(DeleteView):
    model = Item
    success_url = '/items/'
    
def associate_item(request, pokemon_id, item_id):
    Pokemon.objects.get(id=pokemon_id).items.add(item_id)
    return redirect('pokemon-detail', pokemon_id=pokemon_id)

def remove_item(request, pokemon_id, item_id):
    pokemon = Pokemon.objects.get(id=pokemon_id)
    item = Item.objects.get(id=item_id)
    pokemon.items.remove(item)
    
    return redirect('pokemon-detail', pokemon_id=pokemon.id)

pokemoncollector/main_app/templates/about.html
{% extends 'base.html' %} 
{% block content %}
<h1>About the Pokemon Collector</h1>
<hr />
<p class="page-content">
  POKEMON! POKEMON! POKEMON!
</p>
{% endblock %}

pokemoncollector/main_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="" />
    <title>Pokemon Collector</title>
    {% block head %} 
    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
          <img src="" alt="The Pokemon Collector Logo" />
        </a>
      </div>
      <nav>
        <ul>
          <li><a href="{% url 'pokemon-index' %}">All Pokemon</a></li>
          <li><a href="{% url 'item-index' %}">All Items</a></li>
          <li><a href="{% url 'pokemon-create' %}">Add a Pokemon</a></li>
          <li><a href="{% url 'item-create' %}">Add an Item</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
        </ul>
      </nav>
    </header>
    <main>
     {% block content %} 
     {% endblock %}
     </main>
  </body>
</html>

pokemoncollector/main_app/templates/home.html
{% extends 'base.html' %}


{% block content %}
    <h1>Home Page</h1>
{% endblock content %}

pokemoncollector/main_app/templates/main_app/item_confirm_delete.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Item?</h1>
</div>
<h2>Are you sure you want to delete {{ object.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'item-detail' item.id %}" class="btn secondary"> Cancel </a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

pokemoncollector/main_app/templates/main_app/item_detail.html
{% extends 'base.html' %} 
{% load static %}  
{% block content %}

<div class="card" style="border-color: {{ item.color }}">
  <div class="card-bg" style="background-color: {{ item.color }}"></div>
  <div class="card-content">
    <h2>{{ item.name }}</h2>
    <p>{{ item.effect }}</p>
  </div>
</div>
<a href="{% url 'item-update' item.id %}" class="btn warn">Edit</a>
<a href="{% url 'item-delete' item.id %}" class="btn danger">Delete</a>

{% endblock %}

pokemoncollector/main_app/templates/main_app/item_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{object.name}}</h1>
    {% else %}
      <h1>Add an Item</h1>
    {% endif %}
  </div>
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>

{% endblock %}

pokemoncollector/main_app/templates/main_app/item_list.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<section class="page-header">
  <h1>All Pokemon Items</h1>
</section>

<section class="card-container">
  {% for item in item_list %}
    <div class="card" style="border-color: {{ item.color }}">
      <div class="card-bg" style="background-color: {{ item.color }}"></div>
      <a href="{% url 'item-detail' item.id %}">
        <div class="card-content">
          <h2>{{ item.name }}</h2>
          <p>{{ item.effect }}</p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>

{% endblock %}

pokemoncollector/main_app/templates/main_app/pokemon_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Pokemon?</h1>
</div>

<h2>Are you sure you want to delete {{ pokemon.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'pokemon-detail' pokemon.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

pokemoncollector/main_app/templates/main_app/pokemon_form.html
{% extends 'base.html' %}
{% load static %}


{% block head %}
    
{% endblock head %}
    

{% block content %}
<div class="page-header">
    
    {% if object %}
        <h1>Edit {{ object.name }}</h1>
    {% else %}
        <h1>Add a Pokemon</h1>
    {% endif %}
        

  </div>
  
  <form action="" method="post" class="form-container">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>
{% endblock content %}

pokemoncollector/main_app/templates/pokemon/detail.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
<section class="pokemon-container">
  <div class="pokemon-details">
    <h1>{{ pokemon.name }}</h1>
    <p>{{ pokemon.description }}</p>

    <div class="pokemon-actions">
      <a href="{% url 'pokemon-update' pokemon.id %}" class="btn warn">Edit</a>
      <a href="{% url 'pokemon-delete' pokemon.id %}" class="btn danger">Delete</a>
    </div>
  </div>
</section>
<div class="feedings-toy-container">
  <section class="feedings">
    <div class="subsection-title">
      <h2>Feedings</h2>
    </div>

    <h3>Add Feeding</h3>
    <form action="{% url 'add-feeding' pokemon.id %}" method="POST" class='subsection-content'>
      {% csrf_token %}
      {{ feeding_form.as_p }}
      <button type='submit' class='btn submit'>Add Feeding</button>
    </form>

    {% if pokemon.feeding_set.all.count %}
      
    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Meal</th>
        </tr>
      </thead>
      <tbody>
        {% for feeding in pokemon.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </section>
</div>
    {% else %}
      <div class='subsection-content'>
        <p>{{ pokemon.name }} has not been fed!</p>
      </div>

    {% endif %}
    <section class="toys">
      <div class="subsection-title">
        <h2>Items</h2>
      </div>
      <h3>{{ pokemon.name }}'s Items</h3>
  <div class="subsection-content">
    {% if pokemon.items.count %} 
      {% for item in pokemon.items.all %}
        <div class="item-container">
          <div class="color-block" style="background-color: {{ item.color }}"></div>
          <a href="{% url 'item-detail' item.id %}">
            <p>A {{ item.name }}</p>
          </a>
        </div>
        <form action="{% url 'remove-item' pokemon.id item.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger">Remove Item</button>
        </form>        
      {% endfor %} 
    {% else %}
      <p class="no-items">{{item.name}} doesn't have any items!</p>
    {% endif %}
  </div>
  <h3>Available Items</h3>
  <div class="subsection-content">
    {% if items.count %} 
      {% for item in items.all %}
        <div class="item-container">
          <div class="color-block" style="background-color: {{ item.color }}"></div>
          <a href="{% url 'item-detail' item.id %}">
            <p>A {{ item.name }}</p>
          </a>
          <form action="{% url 'associate-item' pokemon.id item.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn submit">Give item</button>
          </form>

        </div>
      {% endfor %} 
    {% else %}
      <p class="all-items">{{pokemon.name}} already has all the available items</p>
    {% endif %}
  </div>
    </section>

{% endblock %}

pokemoncollector/main_app/templates/pokemon/index.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/cats/cat-index.css' %}">
{% endblock head %}

{% block content %}

<section class='page-header'>
	<h1>Pokemon list</h1>
</section>

<section class='card-container'>

	


	{% for pokemon in pokemon %}
		<div class='card'>
			<a href="{% url 'pokemon-detail' pokemon.id %}">
			<div class='card-content'>
				<div class='card-img-container'>
				</div>
				<h2 class='card-title'>{{ pokemon.name }}</h2>
				
				{% if cat.age > 0 %}
					<p>{{ pokemon.age }} year old {{pokemon.name}}</p>
				{% else %}
					<p>An {{ pokemon.type }} type</p>
				{% endif %}
				<p><small>{{ pokemon.description }}</small></p>					
					
			</div>
			</a>
		</div>
	{% endfor %}
		
</section>

{% endblock content %}